version: '3.8'

services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock-service
    ports:
      - "8081:8081"
    environment:
      - WIREMOCK_OPTIONS=--verbose --port 8081
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/__admin"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 