{{/*
=============================================================================
Collateral Umbrella Chart — Helper Templates
=============================================================================
These helpers are used by the Istio networking templates in this directory.
They run in the umbrella chart context, so all values are accessed with the
full path (e.g. .Values.networking.gateway, not .Values.gateway).

The appFullname helper mirrors helm-charts/service-virtualization/_helpers.tpl
so that service names generated here always match those generated by the sv
subchart.
=============================================================================
*/}}

{{/*
Compute the app fullname for service name derivation.
With nameOverride: "service-virtualization" set in sv-global.yaml, the sv
subchart produces fullname = "<release>-service-virtualization". This helper
produces the same value so networking templates target the right services.
*/}}
{{- define "networking.appFullname" -}}
{{- if .Values.networking.appFullnameOverride -}}
{{- .Values.networking.appFullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-service-virtualization" .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}

{{/*
Common labels for all Istio resources created by the umbrella chart.
*/}}
{{- define "networking.labels" -}}
app.kubernetes.io/managed-by: {{ .Release.Service }}
helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
app.kubernetes.io/name: {{ .Release.Name }}-networking
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
