version: '3.8'
services:
  activemq:
    image: rmohr/activemq:5.15.9
    network_mode: host
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    volumes:
      - activemq-data:/opt/activemq/data
    restart: unless-stopped

volumes:
  activemq-data: 