-- V3: DEFAULT NEWID() constraints
--
-- All tables created in V1 (kafka_stubs) and V2 (soap_stubs) already include
-- DEFAULT NEWID() in their CREATE TABLE statements, so no ALTER TABLE is required
-- for those tables.
--
-- Tables for rest_stubs (V4), tibco_stubs (V5), active_mq_stubs and ibmmq_stubs (V6)
-- are created in later migrations and also include DEFAULT NEWID() at creation time.
--
-- This migration is intentionally a no-op; it is kept so that Flyway's version
-- history remains gapless for installations that may have recorded its checksum.
