-- V7: superseded by V6
--
-- This migration previously added flat columns to ibmmq_stubs.  V6 was updated
-- to use JSON blob storage instead of flat columns, making those ALTER TABLE
-- statements unnecessary and incompatible with the new schema.
--
-- This migration is intentionally a no-op.
