apiVersion: v1
kind: Config
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://127.0.0.1:6443
  name: k3s-local
contexts:
- context:
    cluster: k3s-local
    user: k3s-local
  name: k3s-local
current-context: k3s-local
users:
- name: k3s-local
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJZUlvZXlmbVhkQjR3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemN5TlRJMU1qVXdNQjRYRFRJMk1ETXdNekE0TURjek1Gb1hEVEkzTURNdwpNekE0TURjek1Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFaUhoNUVqYW14ejVEWFoKRW1LUVlKZ3ZYMmZGckFTUUtCZGNzc0o5V3dHWG8yMGdQdDMxSFpBSDRrd3o2NEhkdWI3SXNUSHFrcXFKb3U1ZQpwWWZ0bkd1alNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUnZrSlErZm5GenE3aktBUXJXWTkxQXk1ZGkrREFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQWp5VUU2MG0xanlvZlhPajVzaXpVZk9PRCtMK1RvdUVEbnZad2VXaytGdGdDSVFDbmZwRDgvaEVqbUFpcApoWEViS2NXYmQraVFzNVVNcWVnUjlsQ09VQXdPV0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZGpDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFM056STFNalV5TlRBd0hoY05Nall3TXpBek1EZ3dOek13V2hjTk16WXdNakk1TURnd056TXcKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFM056STFNalV5TlRBd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBUVNiN21rbStZRFpOL2h4azYxYWdOcjN5ZzF6ekVkY3VKNU9pNGR5czIzCnJTNDd0OVAxOGhEZXpEZmJRWUhBQUJ5ZE5CdGY2anlFSUNjWjJ2S0pvNFRMbzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVViNUNVUG41eGM2dTR5Z0VLMW1QZApRTXVYWXZnd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ0xhN2p4RHVPSW5TNlVMbDJka0o1eC9ycm1rdXlrTzZwCmxzT21zRjlkZWRZQ0lHeVk5SXcrNGNaN2s2SDZOUlY4MHNub3NoRjZPZkJJSnVkdzBkeENBdzdJCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUZIQkJpYmY5YUlnbGlhbXplVkE4MEI2WVl4Rk5ZSHI2UXhhZWo1VXZUK25vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFU0llSGtTTnFiSFBrTmRrU1lwQmdtQzlmWjhXc0JKQW9GMXl5d24xYkFaZWpiU0ErM2ZVZAprQWZpVERQcmdkMjV2c2l4TWVxU3FvbWk3bDZsaCsyY2F3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
