-- =============================================================================
-- Service Virtualization Platform — Sybase Schema
-- =============================================================================
--
-- Run this script once against the service_virtualization database to create
-- all stub tables. The script is idempotent — each object is only created if
-- it does not already exist.
--
-- Storage pattern: every table uses a two-column JSON-blob design.
--   id        VARCHAR(36)   — UUID primary key, generated by the database
--   stub_data NVARCHAR(MAX) — full stub object serialized as JSON
--
-- Stub fields are queried via JSON_VALUE(stub_data, '$.fieldName'). Indexes
-- are placed on the most-filtered fields: status, userId, and routing keys.
-- =============================================================================

USE service_virtualization;
GO

-- =============================================================================
-- kafka_stubs
-- =============================================================================
IF OBJECT_ID('dbo.kafka_stubs', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.kafka_stubs (
        id        VARCHAR(36)   NOT NULL CONSTRAINT DF_kafka_stubs_id DEFAULT NEWID(),
        stub_data NVARCHAR(MAX) NOT NULL,
        CONSTRAINT PK_kafka_stubs PRIMARY KEY (id)
    );

    CREATE INDEX IDX_kafka_stubs_status
        ON dbo.kafka_stubs (JSON_VALUE(stub_data, '$.status'));

    CREATE INDEX IDX_kafka_stubs_user_id
        ON dbo.kafka_stubs (JSON_VALUE(stub_data, '$.userId'));

    CREATE INDEX IDX_kafka_stubs_request_topic
        ON dbo.kafka_stubs (JSON_VALUE(stub_data, '$.requestTopic'));

    CREATE INDEX IDX_kafka_stubs_response_topic
        ON dbo.kafka_stubs (JSON_VALUE(stub_data, '$.responseTopic'));

    PRINT 'Created table: kafka_stubs';
END
ELSE
    PRINT 'Table already exists, skipping: kafka_stubs';
GO

-- =============================================================================
-- rest_stubs
-- =============================================================================
IF OBJECT_ID('dbo.rest_stubs', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.rest_stubs (
        id        VARCHAR(36)   NOT NULL CONSTRAINT DF_rest_stubs_id DEFAULT NEWID(),
        stub_data NVARCHAR(MAX) NOT NULL,
        CONSTRAINT PK_rest_stubs PRIMARY KEY (id)
    );

    CREATE INDEX IDX_rest_stubs_status
        ON dbo.rest_stubs (JSON_VALUE(stub_data, '$.status'));

    CREATE INDEX IDX_rest_stubs_user_id
        ON dbo.rest_stubs (JSON_VALUE(stub_data, '$.userId'));

    -- Protocol (HTTP/HTTPS) + URL for WireMock routing lookups
    CREATE INDEX IDX_rest_stubs_protocol_url
        ON dbo.rest_stubs (
            JSON_VALUE(stub_data, '$.protocol'),
            JSON_VALUE(stub_data, '$.matchConditions.url')
        );

    PRINT 'Created table: rest_stubs';
END
ELSE
    PRINT 'Table already exists, skipping: rest_stubs';
GO

-- =============================================================================
-- soap_stubs
-- =============================================================================
IF OBJECT_ID('dbo.soap_stubs', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.soap_stubs (
        id        VARCHAR(36)   NOT NULL CONSTRAINT DF_soap_stubs_id DEFAULT NEWID(),
        stub_data NVARCHAR(MAX) NOT NULL,
        CONSTRAINT PK_soap_stubs PRIMARY KEY (id)
    );

    CREATE INDEX IDX_soap_stubs_status
        ON dbo.soap_stubs (JSON_VALUE(stub_data, '$.status'));

    CREATE INDEX IDX_soap_stubs_user_id
        ON dbo.soap_stubs (JSON_VALUE(stub_data, '$.userId'));

    -- SOAPAction is the primary dispatch key for SOAP routing
    CREATE INDEX IDX_soap_stubs_soap_action
        ON dbo.soap_stubs (JSON_VALUE(stub_data, '$.soapAction'));

    PRINT 'Created table: soap_stubs';
END
ELSE
    PRINT 'Table already exists, skipping: soap_stubs';
GO

-- =============================================================================
-- tibco_stubs
-- =============================================================================
IF OBJECT_ID('dbo.tibco_stubs', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.tibco_stubs (
        id        VARCHAR(36)   NOT NULL CONSTRAINT DF_tibco_stubs_id DEFAULT NEWID(),
        stub_data NVARCHAR(MAX) NOT NULL,
        CONSTRAINT PK_tibco_stubs PRIMARY KEY (id)
    );

    CREATE INDEX IDX_tibco_stubs_status
        ON dbo.tibco_stubs (JSON_VALUE(stub_data, '$.status'));

    CREATE INDEX IDX_tibco_stubs_user_id
        ON dbo.tibco_stubs (JSON_VALUE(stub_data, '$.userId'));

    -- Destination type (queue/topic) + name drive message routing
    CREATE INDEX IDX_tibco_stubs_destination
        ON dbo.tibco_stubs (
            JSON_VALUE(stub_data, '$.destinationType'),
            JSON_VALUE(stub_data, '$.destinationName')
        );

    PRINT 'Created table: tibco_stubs';
END
ELSE
    PRINT 'Table already exists, skipping: tibco_stubs';
GO

-- =============================================================================
-- active_mq_stubs
-- =============================================================================
IF OBJECT_ID('dbo.active_mq_stubs', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.active_mq_stubs (
        id        VARCHAR(36)   NOT NULL CONSTRAINT DF_active_mq_stubs_id DEFAULT NEWID(),
        stub_data NVARCHAR(MAX) NOT NULL,
        CONSTRAINT PK_active_mq_stubs PRIMARY KEY (id)
    );

    CREATE INDEX IDX_active_mq_stubs_status
        ON dbo.active_mq_stubs (JSON_VALUE(stub_data, '$.status'));

    CREATE INDEX IDX_active_mq_stubs_user_id
        ON dbo.active_mq_stubs (JSON_VALUE(stub_data, '$.userId'));

    CREATE INDEX IDX_active_mq_stubs_destination
        ON dbo.active_mq_stubs (
            JSON_VALUE(stub_data, '$.destinationType'),
            JSON_VALUE(stub_data, '$.destinationName')
        );

    PRINT 'Created table: active_mq_stubs';
END
ELSE
    PRINT 'Table already exists, skipping: active_mq_stubs';
GO

-- =============================================================================
-- ibmmq_stubs
-- =============================================================================
IF OBJECT_ID('dbo.ibmmq_stubs', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ibmmq_stubs (
        id        VARCHAR(36)   NOT NULL CONSTRAINT DF_ibmmq_stubs_id DEFAULT NEWID(),
        stub_data NVARCHAR(MAX) NOT NULL,
        CONSTRAINT PK_ibmmq_stubs PRIMARY KEY (id)
    );

    CREATE INDEX IDX_ibmmq_stubs_status
        ON dbo.ibmmq_stubs (JSON_VALUE(stub_data, '$.status'));

    CREATE INDEX IDX_ibmmq_stubs_user_id
        ON dbo.ibmmq_stubs (JSON_VALUE(stub_data, '$.userId'));

    -- Destination type + name are the IBM MQ routing keys
    CREATE INDEX IDX_ibmmq_stubs_destination
        ON dbo.ibmmq_stubs (
            JSON_VALUE(stub_data, '$.destinationType'),
            JSON_VALUE(stub_data, '$.destinationName')
        );

    PRINT 'Created table: ibmmq_stubs';
END
ELSE
    PRINT 'Table already exists, skipping: ibmmq_stubs';
GO

PRINT '=== Schema initialization complete ===';
GO
